### ISSUE TITLE
Extra stroke around ad border

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdLiPo#13] opened 2021-08-21 09:31 UTC
should not have green outline

<img width="977" alt="image" src="https://user-images.githubusercontent.com/737638/130317568-8c5b00c5-d2ad-4448-b138-b049a8864237.png">

**Comment by Real-John-Cheung** [comment] 2021-09-01 14:28
I think this is actually caused by the same problem that causes https://github.com/dhowe/AdLiPo/issues/15 and should be fixed with https://github.com/dhowe/AdLiPo/commit/bfefc2c0db1dd87b29248c7d9d25d3975851a7d5 
in https://github.com/dhowe/AdLiPo/commit/3bb4c3d1fd4cfeb3030d97a2f82b123848040fe8 I also add the attribute `border:0!important;` to prevent similar bug

**Closed as completed** 2021-10-09 05:33 UTC
Labels: layout
